title: Networked Selfhood and the Novel
description: >
baseurl: "/selfhood"
url: "https://gwijthoff.github.io/selfhood/"
paginate:	1 # The number of posts to show per page on your homepage
name: "Grant Wythoff"
markdown: kramdown
permalink: none
destination: docs
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
